const LESSON_8 = {
  id: 8,
  title: "Qaama Namaa",
  titleEnglish: "Body Parts",
  icon: "🫀",
  level: "gidduu",
  words: [
    { english: "Head", oromo: "Mataa", example: "My head hurts.", exampleOromo: "Mataan koo na dhagabama.", explanation: "Kutaa qaamaa ol-aanaa." },
    { english: "Hair", oromo: "Rifeensa mataa", example: "Her hair is long.", exampleOromo: "Rifeensi mataa ishee dheeraa dha.", explanation: "Mataa irratti argamu." },
    { english: "Face", oromo: "Fuula", example: "Wash your face.", exampleOromo: "Fuula kee dhiqadhu.", explanation: "Kutaa mataa duraa." },
    { english: "Eye", oromo: "Ija", example: "I have two eyes.", exampleOromo: "Ija lama qaba.", explanation: "Waan itti arginu." },
    { english: "Ear", oromo: "Gurra", example: "I hear with my ears.", exampleOromo: "Gurra koon nan dhaga'a.", explanation: "Waan itti dhageenyu." },
    { english: "Nose", oromo: "Funyaan", example: "The nose smells.", exampleOromo: "Funyaani ni fooyya.", explanation: "Waan itti fool fudhennu." },
    { english: "Mouth", oromo: "Afaan", example: "Open your mouth.", exampleOromo: "Afaan kee bani.", explanation: "Waan itti nyaannu." },
    { english: "Tooth", oromo: "Ilkii", example: "Brush your teeth.", exampleOromo: "Ilkii kee qulqulleessi.", explanation: "Afaan keessa jiru." },
    { english: "Tongue", oromo: "Liloo", example: "The tongue tastes food.", exampleOromo: "Liloon nyaata dhandhama.", explanation: "Afaan keessatti argamu." },
    { english: "Neck", oromo: "Morma", example: "My neck is stiff.", exampleOromo: "Mormi koo jabaateera.", explanation: "Mataa fi adda baasu." },
    { english: "Shoulder", oromo: "Adda", example: "He has broad shoulders.", exampleOromo: "Adda isaa bal'aa dha.", explanation: "Kutaa qaamaa ol-aanaa." },
    { english: "Arm", oromo: "Harka", example: "Raise your arm.", exampleOromo: "Harka kee ol kaasi.", explanation: "Kutaa qaamaa irraa hanga gadaatti." },
    { english: "Hand", oromo: "Harka", example: "Wash your hands.", exampleOromo: "Harka kee dhiqadhu.", explanation: "Kutaa qaamaa wanta qabadhu." },
    { english: "Finger", oromo: "Quba", example: "I have ten fingers.", exampleOromo: "Quba kudhan qaba.", explanation: "Harka keessatti argamu." },
    { english: "Chest", oromo: "Garaa ol", example: "My chest hurts.", exampleOromo: "Garaan koo ol na dhagabama.", explanation: "Kutaa qaamaa fuulduraa." },
    { english: "Stomach", oromo: "Garaa", example: "My stomach is full.", exampleOromo: "Garaan koo guutameera.", explanation: "Bakka nyaatni itti buluu." },
    { english: "Back", oromo: "Dugda", example: "My back is sore.", exampleOromo: "Dugdi koo na dhagabama.", explanation: "Kutaa qaamaa duubaa." },
    { english: "Leg", oromo: "Miila", example: "My legs are tired.", exampleOromo: "Miilli koo dadhabee jira.", explanation: "Kutaa qaamaa gad-aanaa." },
    { english: "Foot", oromo: "Miila", example: "Wash your feet.", exampleOromo: "Miila kee dhiqadhu.", explanation: "Kutaa qaamaa gad-aanaa itti deemnu." },
    { english: "Knee", oromo: "Jilba", example: "My knee hurts.", exampleOromo: "Jilbi koo na dhagabama.", explanation: "Gidduu miilaa." },
    { english: "Heart", oromo: "Onnee", example: "The heart beats.", exampleOromo: "Onneen ni dhaadatti.", explanation: "Qaama dhiiga raabsu." },
    { english: "Blood", oromo: "Dhiiga", example: "Blood is red.", exampleOromo: "Dhiigni diimaa dha.", explanation: "Qaama keessa yaa'u." },
    { english: "Bone", oromo: "Laftoo", example: "Bones are strong.", exampleOromo: "Laftoon jabaata.", explanation: "Qaama cimaa keessaa." },
    { english: "Skin", oromo: "Gogaa", example: "The skin protects us.", exampleOromo: "Gogaan nu eega.", explanation: "Qaama alaa haguugu." },
    { english: "Brain", oromo: "Sammuu", example: "The brain thinks.", exampleOromo: "Sammuun yaada.", explanation: "Qaama yaadu." },
    { english: "Lip", oromo: "Bibiiqa", example: "Her lips are red.", exampleOromo: "Bibiqaan ishee diimaa dha.", explanation: "Afaan alaa haguugu." },
    { english: "Cheek", oromo: "Ceedaa", example: "Her cheeks are rosy.", exampleOromo: "Ceedaan ishee diimtuu dha.", explanation: "Kutaa fuulaa." },
    { english: "Elbow", oromo: "Qubee", example: "I hurt my elbow.", exampleOromo: "Qubee koo nan miidhe.", explanation: "Gidduu harkaa." },
    { english: "Body", oromo: "Qaama", example: "Exercise is good for the body.", exampleOromo: "Sochiin qaamaaf gaarii dha.", explanation: "Qaama namaa guutuu." },
    { english: "Pain", oromo: "Dhukkuba", example: "I feel pain.", exampleOromo: "Dhukkuba nan dhagahama.", explanation: "Miidhaa qaamaa." }
  ]
};