const LESSON_9 = {
  id: 9,
  title: "Uffata fi Meeshaa Uffannoo",
  titleEnglish: "Clothing & Accessories",
  icon: "👕",
  level: "gidduu",
  words: [
    { english: "Clothes", oromo: "Uffata", example: "I need to wash my clothes.", exampleOromo: "Uffata koo dhiquu qaba.", explanation: "Waan uffannu hundaa." },
    { english: "Shirt", oromo: "Shaartii", example: "He is wearing a blue shirt.", exampleOromo: "Isaan shaartii cuqulisa uffatee jira.", explanation: "Uffata qaama olii." },
    { english: "T-shirt", oromo: "T-shaartii", example: "I like to wear t-shirts in summer.", exampleOromo: "Bonaa keessa t-shaartii uffachuun nan jaaladha.", explanation: "Shaartii gogaa irraa hojjetame." },
    { english: "Pants", oromo: "Ximaaduu", example: "These pants are too tight.", exampleOromo: "Ximaaduun kun baay'ee cimdha.", explanation: "Uffata miilaaf." },
    { english: "Jeans", oromo: "Jiinzii", example: "She bought new jeans yesterday.", exampleOromo: "Isheen kaleessa jiinzii haaraa bitte.", explanation: "Ximaaduu cottee irraa hojjetame." },
    { english: "Dress", oromo: "Uffata dubartii", example: "The dress is very beautiful.", exampleOromo: "Uffatni dubartii baay'ee miidhaga dha.", explanation: "Uffata dubartootaa guutuu." },
    { english: "Skirt", oromo: "Sikiirtii", example: "She is wearing a long skirt.", exampleOromo: "Isheen sikiirtii dheeraa uffatteetti.", explanation: "Uffata dubartootaa gadii." },
    { english: "Jacket", oromo: "Jaakettii", example: "Put on your jacket, it's cold.", exampleOromo: "Jaakettii kee uffadhu, qorraa dha.", explanation: "Uffata qorraa irraa eegu." },
    { english: "Coat", oromo: "Kotii", example: "I need a warm coat for winter.", exampleOromo: "Bonaa keessatti kotii ho'aa nan barbaada.", explanation: "Uffata qabanaa'aa guddaa." },
    { english: "Sweater", oromo: "Siwaatarii", example: "This sweater is very comfortable.", exampleOromo: "Siwaatariin kun baay'ee kan nama boqochiisu dha.", explanation: "Uffata ho'aa gogaa irraa hojjetame." },
    { english: "Shoes", oromo: "Mika'aa", example: "I need new shoes for school.", exampleOromo: "Mana barumsaaf mika'aa haaraa nan barbaada.", explanation: "Waan miila uffannu." },
    { english: "Sneakers", oromo: "Siniikarii", example: "He runs fast in his sneakers.", exampleOromo: "Isaan siniikarii isaa keessatti saffisa fiiga.", explanation: "Mika'aa ispoortii." },
    { english: "Sandals", oromo: "Sandaalii", example: "I wear sandals in the summer.", exampleOromo: "Bonaa keessatti sandaalii nan uffadha.", explanation: "Mika'aa bonnaa." },
    { english: "Boots", oromo: "Buutsii", example: "Farmers wear boots in the field.", exampleOromo: "Qotee bulaan buutsii dirree keessatti uffata.", explanation: "Mika'aa dheeraa cimdha." },
    { english: "Socks", oromo: "Sookii", example: "Don't forget to wear socks.", exampleOromo: "Sookii uffachuu hin dagatiin.", explanation: "Waan miila keessatti uffatu." },
    { english: "Hat", oromo: "Koofiyaa", example: "The sun is hot, wear a hat.", exampleOromo: "Aduun ho'aa dha, koofiyaa uffadhu.", explanation: "Waan mataa haguugu." },
    { english: "Cap", oromo: "Kaappii", example: "He wears a baseball cap.", exampleOromo: "Isaan kaappii beezbooolii uffata.", explanation: "Koofiyaa xiqqoo." },
    { english: "Scarf", oromo: "Iskaarfii", example: "She wrapped a scarf around her neck.", exampleOromo: "Isheen iskaarfii morma ishee marsite.", explanation: "Uffata mormaaf qorraa irraa eegu." },
    { english: "Gloves", oromo: "Giraandii", example: "Wear gloves when it's cold.", exampleOromo: "Yeroo qorraa ta'u giraandii uffadhu.", explanation: "Waan harkaa qorraa irraa eegu." },
    { english: "Belt", oromo: "Beeltii", example: "He tightened his belt.", exampleOromo: "Isaan beeltii isaa cimsate.", explanation: "Waan ximaaduu qabatu." },
    { english: "Tie", oromo: "Taayii", example: "He wears a tie to work.", exampleOromo: "Isaan hojiitti taayii uffata.", explanation: "Uffata shaartii irratti miidhaginaaf." },
    { english: "Uniform", oromo: "Yuunifoormii", example: "Students must wear uniforms.", exampleOromo: "Barattoonni yuunifoormii uffachuu qabu.", explanation: "Uffata addaa dhaabbataaf." },
    { english: "Pajamas", oromo: "Pijaamaa", example: "I change into pajamas before bed.", exampleOromo: "Osoon hin ciisin dura pijaamaa jijjiiradha.", explanation: "Uffata ciisuuf." },
    { english: "Underwear", oromo: "Uffata keessaa", example: "You should wash underwear separately.", exampleOromo: "Uffata keessaa adda baasuun dhiquu qabda.", explanation: "Uffata qaama keessaa." },
    { english: "Raincoat", oromo: "Kotii roobaa", example: "Take your raincoat, it might rain.", exampleOromo: "Kotii roobaa kee fudhadhu, roobuu danda'a.", explanation: "Uffata rooba irraa eegu." },
    { english: "Pocket", oromo: "Laafaa", example: "I put my phone in my pocket.", exampleOromo: "Bilbila koo laafaa koo keessa naqadhe.", explanation: "Bakka uffata keessatti waan xixiqqaa kaa'u." },
    { english: "Button", oromo: "Butuunii", example: "The button fell off my shirt.", exampleOromo: "Butuuniin shaartii koo irraa kufe.", explanation: "Waan uffata cufu." },
    { english: "Zipper", oromo: "Zippirii", example: "Zip up your jacket.", exampleOromo: "Jaakettii kee zippirii godhi.", explanation: "Waan uffata baniisuu fi cufu." },
    { english: "Size", oromo: "Hamma", example: "What size do you wear?", exampleOromo: "Hamma meeqa uffatta?", explanation: "Guddina uffataa." },
    { english: "Color", oromo: "Halluu", example: "I like the color of this dress.", exampleOromo: "Halluu uffata kana nan jaaladha.", explanation: "Bifa uffataa." },
    { english: "Wear", oromo: "Uffachuu", example: "What are you wearing today?", exampleOromo: "Har'a maal uffatteetta?", explanation: "Uffata qaama irratti baachuu." },
    { english: "Take off", oromo: "Buusuu", example: "Take off your shoes at the door.", exampleOromo: "Balbala irratti mika'aa kee buusi.", explanation: "Uffata qaama irraa baasuu." },
    { english: "Put on", oromo: "Uffachuu", example: "Put on your coat, it's cold outside.", exampleOromo: "Kotii kee uffadhu, alatti qorraa dha.", explanation: "Uffata qaama irratti baachuu." },
    { english: "Fit", oromo: "Taaluu", example: "These shoes fit perfectly.", exampleOromo: "Mika'aan kun sirriitti na taala.", explanation: "Uffata qaamaaf ta'uu." },
    { english: "Tight", oromo: "Cimaa", example: "This shirt is too tight.", exampleOromo: "Shaartiin kun baay'ee cimdha.", explanation: "Uffata qaama cimsu." },
    { english: "Loose", oromo: "Laafaa", example: "I prefer loose clothing.", exampleOromo: "Uffata laafaa nan filadha.", explanation: "Uffata qaama hin cimsine." },
    { english: "Comfortable", oromo: "Kan nama boqochiisu", example: "These sneakers are very comfortable.", exampleOromo: "Siniikaariin kun baay'ee kan nama boqochiisu dha.", explanation: "Uffata itti fayyadamuuf salphaa." },
    { english: "Expensive", oromo: "Gatii guddaa", example: "That dress is very expensive.", exampleOromo: "Uffatni dubartii sun baay'ee gatii guddaa qaba.", explanation: "Waan gatii guddaa qabu." },
    { english: "Cheap", oromo: "Gatii xiqqaa", example: "I bought cheap socks.", exampleOromo: "Sookii gatii xiqqaa qabu bite.", explanation: "Waan gatii xiqqaa qabu." },
    { english: "Fashion", oromo: "Faashinii", example: "She follows the latest fashion.", exampleOromo: "Isheen faashinii haaraa hordoffi.", explanation: "Akkaataa uffataa ammayyaa." }
  ]
};