const LESSON_10 = {
  id: 10,
  title: "Meeshaa Manaa fi Kutaa Mana",
  titleEnglish: "House Items & Rooms",
  icon: "🏠",
  level: "gidduu",
  words: [
    { english: "House", oromo: "Mana", example: "Our house is near the school.", exampleOromo: "Manaan keenya mana barumsaa biraa jira.", explanation: "Bakka keessa jiraannu." },
    { english: "Room", oromo: "Kutaa mana", example: "My room is upstairs.", exampleOromo: "Kutaan mana koo ol jira.", explanation: "Bakka mana keessaa adda ba'e." },
    { english: "Kitchen", oromo: "Kushinaa", example: "Mom is cooking in the kitchen.", exampleOromo: "Haadha koo kushinaa keessatti nyaata bilchessiti.", explanation: "Bakka nyaata itti qopheessinu." },
    { english: "Bedroom", oromo: "Kutaa ciisichaa", example: "I sleep in my bedroom.", exampleOromo: "Kutaa ciisichaa koo keessatti nan ciisa.", explanation: "Bakka itti ciisnu." },
    { english: "Bathroom", oromo: "Kutaa dhiqannaa", example: "The bathroom is clean.", exampleOromo: "Kutaan dhiqannaa qulqulluu dha.", explanation: "Bakka itti dhiqannu." },
    { english: "Living room", oromo: "Kutaa keessummaa", example: "We watch TV in the living room.", exampleOromo: "Kutaa keessummaa keessatti TV ilaalla.", explanation: "Bakka keessummaa fi boqonnaa." },
    { english: "Door", oromo: "Balbala", example: "Please close the door.", exampleOromo: "Maaloo balbala cufi.", explanation: "Bakka mana seennee fi baanu." },
    { english: "Window", oromo: "Fenestraa", example: "Open the window for fresh air.", exampleOromo: "Qilleensa qabanaa'aaf fenestraa bani.", explanation: "Bakka ifaa fi qilleensaaf." },
    { english: "Wall", oromo: "Dallaa", example: "The walls are white.", exampleOromo: "Dallaan adii dha.", explanation: "Kutaa mana adda baasu." },
    { english: "Floor", oromo: "Lafaa mana", example: "The floor is wet.", exampleOromo: "Lafti manaa jiidha dha.", explanation: "Bakka irratti deemnu." },
    { english: "Ceiling", oromo: "Waaqaa mana", example: "The ceiling is very high.", exampleOromo: "Waaqaan mana baay'ee dheeraa dha.", explanation: "Kutaa mana ol-aanaa." },
    { english: "Bed", oromo: "Siree", example: "I made my bed this morning.", exampleOromo: "Ganama har'aa siree koo nan qopheesse.", explanation: "Bakka itti ciisnu." },
    { english: "Pillow", oromo: "Tira", example: "I need a soft pillow.", exampleOromo: "Tira laafaa nan barbaada.", explanation: "Waan mataa irratti ciisnu." },
    { english: "Blanket", oromo: "Hagarii", example: "Cover yourself with a blanket.", exampleOromo: "Hagariin of haguugi.", explanation: "Waan qorraa irraa eegu ciisichaa keessatti." },
    { english: "Table", oromo: "Minjaala", example: "The books are on the table.", exampleOromo: "Kitaabni minjaala irratti jira.", explanation: "Meeshaa waan irratti kaa'u." },
    { english: "Chair", oromo: "Teessoo", example: "Please sit on the chair.", exampleOromo: "Maaloo teessoo irratti taa'i.", explanation: "Meeshaa itti taa'u." },
    { english: "Sofa", oromo: "Sofaa", example: "The sofa is very comfortable.", exampleOromo: "Sofaan kun baay'ee kan nama boqochiisu dha.", explanation: "Teessoo guddaa boqonnaaf." },
    { english: "Lamp", oromo: "Ibsaa", example: "Turn on the lamp, it's dark.", exampleOromo: "Ibsaa ibsi, dukkana dha.", explanation: "Meeshaa ifa kennu." },
    { english: "Television", oromo: "TV", example: "We watch news on television.", exampleOromo: "Oduu TV irratti ilaalla.", explanation: "Meeshaa mul'ata fi sagalee agarsiisu." },
    { english: "Refrigerator", oromo: "Firijii", example: "Put the milk in the refrigerator.", exampleOromo: "Aannan firijii keessa naqi.", explanation: "Meeshaa nyaata qabanaa'esuu." },
    { english: "Stove", oromo: "Iddaa", example: "She cooks on the stove.", exampleOromo: "Isheen iddaa irratti nyaata bilchessiti.", explanation: "Meeshaa nyaata itti bilcheessinu." },
    { english: "Oven", oromo: "Oofanii", example: "The cake is in the oven.", exampleOromo: "Keekiin oofanii keessa jira.", explanation: "Meeshaa nyaata itti bilcheessinu ho'inaan." },
    { english: "Sink", oromo: "Sinkii", example: "Wash your hands in the sink.", exampleOromo: "Harka kee sinkii keessatti dhiqadhu.", explanation: "Bakka bishaaniif itti fayyadamnu." },
    { english: "Toilet", oromo: "Huccuu", example: "The toilet is downstairs.", exampleOromo: "Huccuun gad jira.", explanation: "Bakka itti qulqulleeffannu." },
    { english: "Shower", oromo: "Shaawarii", example: "I take a shower every morning.", exampleOromo: "Ganama hundaa shaawarii nan fudhadha.", explanation: "Bakka itti dhiqannu." },
    { english: "Mirror", oromo: "Mul'ata", example: "She looked at herself in the mirror.", exampleOromo: "Isheen mul'ata keessatti of ilaalte.", explanation: "Meeshaa of itti ilaallu." },
    { english: "Clock", oromo: "Sa'aatii", example: "The clock shows 3 o'clock.", exampleOromo: "Sa'aatiin sa'aatii sadii agarsiisa.", explanation: "Meeshaa yeroo agarsiisu." },
    { english: "Picture", oromo: "Suuraa", example: "There are pictures on the wall.", exampleOromo: "Dallaa irratti suuraa jira.", explanation: "Waan miidhaginaaf fannifamu." },
    { english: "Curtain", oromo: "Kaartina", example: "Close the curtain, the sun is bright.", exampleOromo: "Kaartina cufi, aduun ifaa dha.", explanation: "Waan fenestraa haguugu." },
    { english: "Carpet", oromo: "Kaarpitii", example: "The carpet is very soft.", exampleOromo: "Kaarpitiin kun baay'ee laafaa dha.", explanation: "Waan lafa mana haguugu." },
    { english: "Key", oromo: "Furtuu", example: "I lost my house key.", exampleOromo: "Furtuu mana koo nan dhose.", explanation: "Waan balbala itti banuu." },
    { english: "Lock", oromo: "Cufaa", example: "Lock the door when you leave.", exampleOromo: "Yeroo baatu balbala cufi.", explanation: "Meeshaa balbala cufu." },
    { english: "Stairs", oromo: "Jijjiiramaa", example: "Be careful on the stairs.", exampleOromo: "Jijjiiramaa irratti of eeggadhu.", explanation: "Bakka ol fi gad itti deemnu." },
    { english: "Roof", oromo: "Waaqaa", example: "The roof needs repair.", exampleOromo: "Waqaa mana supha barbaada.", explanation: "Kutaa mana ol-aanaa haguugu." },
    { english: "Garden", oromo: "Jardina", example: "There are flowers in the garden.", exampleOromo: "Jardina keessatti daraara jira.", explanation: "Bakka alatti biqiltuu itti dhaabnu." },
    { english: "Fence", oromo: "Dallaa alaa", example: "The fence surrounds the house.", exampleOromo: "Dallaan alaan mana marsa.", explanation: "Waan mana eegu." },
    { english: "Garage", oromo: "Mana konkolaataa", example: "The car is in the garage.", exampleOromo: "Konkolaataan mana konkolaataa keessa jirti.", explanation: "Bakka konkolaataa itti kufnu." },
    { english: "Clean", oromo: "Qulqulluu", example: "The house is very clean.", exampleOromo: "Manaan baay'ee qulqulluu dha.", explanation: "Waan xuraa hin qabne." },
    { english: "Dirty", oromo: "Xuraa'aa", example: "The floor is dirty.", exampleOromo: "Lafti manaa xuraa'aa dha.", explanation: "Waan xuraa qabu." },
    { english: "Furniture", oromo: "Meeshaa mana guutuu", example: "We bought new furniture.", exampleOromo: "Meeshaa mana guutuu haaraa binne.", explanation: "Meeshaa mana keessaa guutuu." }
  ]
};