const LESSON_12 = {
  id: 12,
  title: "Hojii fi Ogummaa",
  titleEnglish: "Professions & Jobs",
  icon: "👨‍⚕️",
  level: "gidduu",
  words: [
    { english: "Job", oromo: "Hojii", example: "He found a new job last week.", exampleOromo: "Isaan torban darbe hojii haaraa argatan.", explanation: "Hojii kaffaltii argachuuf hojjetamu." },
    { english: "Work", oromo: "Hojjachuu", example: "I work from Monday to Friday.", exampleOromo: "Wiixata hanga Jimaataatti nan hojjedha.", explanation: "Sochii kaffaltii argachuuf godhamu." },
    { english: "Doctor", oromo: "Ogeessa fayyaa", example: "The doctor examines the patient.", exampleOromo: "Ogeessi fayyaa dhukkubsataa qorata.", explanation: "Namni dhukkubsattoota yaalu." },
    { english: "Nurse", oromo: "Ogeettii fayyaa gargaartuu", example: "The nurse gives medicine to patients.", exampleOromo: "Ogeettiin fayyaa gargaartuu qoricha dhukkubsattoota kenniti.", explanation: "Namni ogeessa fayyaa gargaaru." },
    { english: "Teacher", oromo: "Barsiisaa", example: "My teacher explains lessons clearly.", exampleOromo: "Barsiisaan koo barnoota ifatti ibsa.", explanation: "Namni barattoota barsiisu." },
    { english: "Student", oromo: "Barataa", example: "The student studies hard for exams.", exampleOromo: "Barataaan qormaataaf ciminaan barata.", explanation: "Namni mana barumsaatti baratu." },
    { english: "Engineer", oromo: "Injinari", example: "The engineer designed the bridge.", exampleOromo: "Injinarri rikibaa sana dizaayinii godhe.", explanation: "Namni waan ijaaru ykn hojjetu dizaayinii godhu." },
    { english: "Lawyer", oromo: "Ogeessa seeraa", example: "The lawyer defended the client in court.", exampleOromo: "Ogeessi seeraa maamilaa mana murtii keessatti ittisaniiru.", explanation: "Namni seeraadhaan namoota gargaaru." },
    { english: "Police officer", oromo: "Poolisii", example: "The police officer caught the thief.", exampleOromo: "Poolisiin saamtichaa qabe.", explanation: "Namni nageenya ummataa eegu." },
    { english: "Soldier", oromo: "Waraana", example: "The soldier protects the country.", exampleOromo: "Waraanni biyyaa ni eega.", explanation: "Namni biyya eeguuf leenjifame." },
    { english: "Farmer", oromo: "Qotee bulaa", example: "The farmer grows crops in the field.", exampleOromo: "Qotee bulaan dirree keessatti midhaa facaasa.", explanation: "Namni lafa irratti midhaa oomishu." },
    { english: "Driver", oromo: "Konkolaachisaa", example: "The driver takes passengers to the airport.", exampleOromo: "Konkolaachisaan fe'amtoota gara buufata xiyyaaraatti geessa.", explanation: "Namni konkolaataa konkolaachisu." },
    { english: "Chef", oromo: "Ogeessa nyaataa", example: "The chef cooks delicious food.", exampleOromo: "Ogeessi nyaataa nyaata mi'aawaa bilchessa.", explanation: "Namni mana nyaataatti nyaata qopheessu." },
    { english: "Waiter", oromo: "Tajaajilaa", example: "The waiter brought our food quickly.", exampleOromo: "Tajaajilaan nyaata keenya saffisaan nuuf fide.", explanation: "Namni mana nyaataatti keessumoota tajaajilu." },
    { english: "Shopkeeper", oromo: "Daldalaa", example: "The shopkeeper sells fruits and vegetables.", exampleOromo: "Daldalaan muduraa fi kuduraa gurgura.", explanation: "Namni suuqii keessatti meeshaa gurguru." },
    { english: "Businessman", oromo: "Daldalaa guddaa", example: "The businessman owns many companies.", exampleOromo: "Daldalaan guddaan dhaabbilee hedduu qaba.", explanation: "Namni daldala guddaa godhu." },
    { english: "Accountant", oromo: "Herregessaa", example: "The accountant manages the company's money.", exampleOromo: "Herregessaan maallaqa dhaabbataa ni bulcha.", explanation: "Namni herrega maallaqaa to'atu." },
    { english: "Banker", oromo: "Hojjetaa baankii", example: "The banker helps customers with loans.", exampleOromo: "Hojjetaan baankii maamiloota liqii gargaara.", explanation: "Namni baankii keessatti hojjetu." },
    { english: "Architect", oromo: "Dizaayinarii mana", example: "The architect designed a beautiful house.", exampleOromo: "Dizaayinariin mana mana miidhagina qabu dizaayinii godhe.", explanation: "Namni mana ijaaruuf karoora baasu." },
    { english: "Carpenter", oromo: "Ogeessa mukaa", example: "The carpenter made wooden furniture.", exampleOromo: "Ogeessi mukaa meeshaa mana mukaa hojjete.", explanation: "Namni mukaa irraa meeshaa hojjetu." },
    { english: "Electrician", oromo: "Ogeessa ibsaa", example: "The electrician fixed the broken wires.", exampleOromo: "Ogeessi ibsaa waayirii cabe suphe.", explanation: "Namni sirna ibsaa suphu." },
    { english: "Plumber", oromo: "Ogeessa bishaanii", example: "The plumber repaired the leaking pipe.", exampleOromo: "Ogeessi bishaanii tuuboo dhangala'aa suphe.", explanation: "Namni sirna bishaanii suphu." },
    { english: "Mechanic", oromo: "Ogeessa suphaa", example: "The mechanic fixed my car.", exampleOromo: "Ogeessi suphaa konkolaataa koo suphe.", explanation: "Namni meeshaa cabsame suphu." },
    { english: "Pilot", oromo: "Balali'isaa", example: "The pilot flies the airplane safely.", exampleOromo: "Balali'isaan xiyyaara nagaan balali'sa.", explanation: "Namni xiyyaara oofu." },
    { english: "Sailor", oromo: "Barbaadaa galaana", example: "The sailor works on a big ship.", exampleOromo: "Barbaadaan galaana doonii guddittii irratti hojjeta.", explanation: "Namni doonii irratti hojjetu." },
    { english: "Artist", oromo: "Aartistii", example: "The artist painted a beautiful picture.", exampleOromo: "Aartistiin suuraa miidhagina qabu sacaare.", explanation: "Namni aartii hojjetu." },
    { english: "Musician", oromo: "Faasuu", example: "The musician plays the guitar well.", exampleOromo: "Faasuun gitaarii gaarii taphata.", explanation: "Namni faaruu hojjetu." },
    { english: "Writer", oromo: "Barreessaa", example: "The writer published a new book.", exampleOromo: "Barreessaan kitaaba haaraa maxxanse.", explanation: "Namni waan barreessu." },
    { english: "Journalist", oromo: "Gabaasaa", example: "The journalist reports the news.", exampleOromo: "Gabaasaan oduu gabaasa.", explanation: "Namni oduu gabaasu." },
    { english: "Scientist", oromo: "Ogeessa saayinsii", example: "The scientist discovered a new medicine.", exampleOromo: "Ogeessi saayinsii qoricha haaraa argate.", explanation: "Namni qorannoo saayinsii godhu." },
    { english: "Office", oromo: "Waajjira", example: "I work in an office downtown.", exampleOromo: "Waajjira gidduu magaalaa keessatti nan hojjedha.", explanation: "Bakka hojii itti hojjenyu." },
    { english: "Salary", oromo: "Mindaa", example: "He receives his salary every month.", exampleOromo: "Isaan ji'a hundaa mindaa isaa ni argata.", explanation: "Maallaqa hojiitif ji'a ji'aan kaffalamu." },
    { english: "Boss", oromo: "Abbaa hojii", example: "My boss is very strict.", exampleOromo: "Abbaan hojii koo baay'ee cimaa dha.", explanation: "Namni hojjettoota bulchu." },
    { english: "Employee", oromo: "Hojjetaa", example: "The company has 50 employees.", exampleOromo: "Dhaabbatni hojjetaa 50 qaba.", explanation: "Namni dhaabbataaf hojjetu." },
    { english: "Interview", oromo: "Gaaffii deebii hojiif", example: "I have a job interview tomorrow.", exampleOromo: "Boru gaaffii deebii hojiif qaba.", explanation: "Marii hojii argachuuf godhamu." },
    { english: "Resume", oromo: "Gabaasa jireenya", example: "She sent her resume to three companies.", exampleOromo: "Isheen gabaasa jireenya ishee gara dhaabbilee sadiitti ergite.", explanation: "Waan muuxannoo fi barnoota nama agarsiisu." },
    { english: "Experience", oromo: "Muuxannoo", example: "He has five years of experience.", exampleOromo: "Isaan muuxannoo waggaa shan qabu.", explanation: "Waan duraan hojjetame irraa barame." },
    { english: "Skill", oromo: "Dandeettii", example: "Communication is an important skill.", exampleOromo: "Qunnamtiin dandeettii barbaachisaa dha.", explanation: "Dandeettii addaa hojii keessatti." },
    { english: "Retire", oromo: "Hojii dhiisuu", example: "My father retired last year.", exampleOromo: "Abbaan koo waggaa darbe hojii dhiise.", explanation: "Umuriin booda hojii dhiisuu." },
    { english: "Promotion", oromo: "Ol guddina", example: "She got a promotion at work.", exampleOromo: "Isheen hojii irratti ol guddina argatte.", explanation: "Sadarkaa hojii irratti ol ba'uu." }
  ]
};