const LESSON_11 = {
  id: 11,
  title: "Imala fi Konkolaataa",
  titleEnglish: "Transportation & Travel",
  icon: "🚗",
  level: "gidduu",
  words: [
    { english: "Car", oromo: "Konkolaataa", example: "My father drives a car to work.", exampleOromo: "Abbaan koo konkolaataadhaan hojiitti konkolaachisa.", explanation: "Meeshaa imalaaf namoota afur ta'u." },
    { english: "Bus", oromo: "Baasii", example: "I take the bus to school.", exampleOromo: "Baasiidhaan mana barumsaatti deema.", explanation: "Konkolaataa guddaa namoota hedduu baatu." },
    { english: "Taxi", oromo: "Taaksii", example: "Let's take a taxi to the airport.", exampleOromo: "Taaksiidhaan gara buufata xiyyaaraatti deemna.", explanation: "Konkolaataa kireeffamu." },
    { english: "Truck", oromo: "Trakii", example: "The truck carries heavy loads.", exampleOromo: "Trakiin fe'aa ulfaataa baata.", explanation: "Konkolaataa guddaa fe'aa baatu." },
    { english: "Motorcycle", oromo: "Mootorootaa", example: "He rides a motorcycle very fast.", exampleOromo: "Isaan mootorootaadhaan baay'ee saffisa.", explanation: "Konkolaataa miila lama qabu." },
    { english: "Bicycle", oromo: "Biskileeta", example: "I ride my bicycle to the park.", exampleOromo: "Biskileeta koon gara paarkeetti deema.", explanation: "Konkolaataa miilaa fiigichaadhaan socho'u." },
    { english: "Train", oromo: "Tireenii", example: "The train arrives at 5 PM.", exampleOromo: "Tireeniin sa'aatii shanii galgalaan dhufa.", explanation: "Konkolaataa baaburaa irratti deemtu." },
    { english: "Airplane", oromo: "Xiyyaara", example: "The airplane flies very high.", exampleOromo: "Xiyyaarri baay'ee ol ni balali'a.", explanation: "Meeshaa qilleensa keessa deemtu." },
    { english: "Boat", oromo: "Doonii", example: "We crossed the river by boat.", exampleOromo: "Dooniidhaan laga qaxxaamurre.", explanation: "Meeshaa bishaan irratti deemtu." },
    { english: "Ship", oromo: "Doonii guddittii", example: "The ship carries many containers.", exampleOromo: "Dooniin guddittiin konteenarii hedduu baatti.", explanation: "Meeshaa bishaan guddaa irratti deemtu." },
    { english: "Driver", oromo: "Konkolaachisaa", example: "The driver is very careful.", exampleOromo: "Konkolaachisaan baay'ee of eeggannoo qaba.", explanation: "Namni konkolaataa konkolaachisu." },
    { english: "Passenger", oromo: "Fe'amaa", example: "The bus has many passengers.", exampleOromo: "Baasiin fe'amaa hedduu qabdi.", explanation: "Namni konkolaataa keessa imalu." },
    { english: "Road", oromo: "Karaa", example: "The road is very long.", exampleOromo: "Karaan baay'ee dheeraa dha.", explanation: "Bakka itti deemnu." },
    { english: "Street", oromo: "Daandii", example: "Turn left at the next street.", exampleOromo: "Daandii itti aanutti gara bitaatti jijjiiri.", explanation: "Karaa magaalaa keessaa." },
    { english: "Highway", oromo: "Karaa guddittii", example: "The highway connects two cities.", exampleOromo: "Karaan guddittiin magaalaa lama walqunnamsiisti.", explanation: "Karaa guddaa fi saffisaa." },
    { english: "Bridge", oromo: "Rikibaa", example: "We crossed the bridge over the river.", exampleOromo: "Rikibaa laga irratti qaxxaamurre.", explanation: "Bakka laga ykn sulula irratti darbu." },
    { english: "Traffic", oromo: "Tiraafikaa", example: "There is heavy traffic today.", exampleOromo: "Har'a tiraafikaan ulfaataa dha.", explanation: "Sochiin konkolaataa karaa irratti." },
    { english: "Accident", oromo: "Balaa", example: "There was a car accident yesterday.", exampleOromo: "Kaleessa balaan konkolaataa ture.", explanation: "Taan konkolaataan walitti bu'u." },
    { english: "Speed", oromo: "Saffisa", example: "Don't drive at high speed.", exampleOromo: "Saffisa guddaadhaan hin konkolaachiisiin.", explanation: "Akkamitti saffisa socho'uu." },
    { english: "Fast", oromo: "Saffisaa", example: "This car is very fast.", exampleOromo: "Konkolaataan kun baay'ee saffisaa dha.", explanation: "Kan saffisa socho'u." },
    { english: "Slow", oromo: "Suuta", example: "Drive slowly in the city.", exampleOromo: "Magaalaa keessatti suuta konkolaachiisi.", explanation: "Kan suuta socho'u." },
    { english: "Stop", oromo: "Dhaabi", example: "Stop at the red light.", exampleOromo: "Ibsaa diimaa irratti dhaabi.", explanation: "Sochii dhaabuu." },
    { english: "Go", oromo: "Deemi", example: "Go straight for two kilometers.", exampleOromo: "Kiloomitara lamaaf kallattiin deemi.", explanation: "Sochii itti fufuu." },
    { english: "Turn", oromo: "Jijjiiri", example: "Turn right at the corner.", exampleOromo: "Kutaa irratti gara mirgaatti jijjiiri.", explanation: "Kallattii jijjiiruu." },
    { english: "Left", oromo: "Bita", example: "Turn left at the traffic light.", exampleOromo: "Ibsaa tiraafikaa irratti gara bitaatti jijjiiri.", explanation: "Kallattii bitaa." },
    { english: "Right", oromo: "Mirga", example: "The school is on the right side.", exampleOromo: "Manaan barumsaa gama mirgaa jira.", explanation: "Kallattii mirgaa." },
    { english: "Straight", oromo: "Kallattii", example: "Go straight until you see the bank.", exampleOromo: "Baankii argitutti kallattiin deemi.", explanation: "Kallattii qajeelaa." },
    { english: "Near", oromo: "Bira", example: "The market is near my house.", exampleOromo: "Gabaa manaa koo bira jira.", explanation: "Fageenya xiqqoo." },
    { english: "Far", oromo: "Fagoo", example: "The airport is far from here.", exampleOromo: "Buufanni xiyyaaraa asirraa fagoo dha.", explanation: "Fageenya guddaa." },
    { english: "Map", oromo: "Kaartaa", example: "I use a map to find the way.", exampleOromo: "Karaa barbaaduuf kaartaa nan fayyadama.", explanation: "Waan kallattii agarsiisu." },
    { english: "Ticket", oromo: "Tikaatii", example: "I bought a bus ticket.", exampleOromo: "Tikaatii baasii bite.", explanation: "Waan imalaaf kaffalamu." },
    { english: "Station", oromo: "Buufata", example: "The bus station is downtown.", exampleOromo: "Buufanni baasii gidduu magaalaa jira.", explanation: "Bakka konkolaataan itti dhaabbatu." },
    { english: "Airport", oromo: "Buufata xiyyaara", example: "We arrived at the airport early.", exampleOromo: "Buufata xiyyaaraatti dursee geenye.", explanation: "Bakka xiyyaarri itti ka'u fi bu'u." },
    { english: "Travel", oromo: "Imaluu", example: "I love to travel to new places.", exampleOromo: "Bakka haaraa imaluun nan jaaladha.", explanation: "Bakka biraatti deemuu." },
    { english: "Journey", oromo: "Imala", example: "The journey took three hours.", exampleOromo: "Imalli sa'aatii sadii fudhate.", explanation: "Sochiin bakka tokkoo gara biraatti." },
    { english: "Trip", oromo: "Imala gabaabaa", example: "We went on a trip to the mountains.", exampleOromo: "Gara gaaratti imala gabaabaa deemne.", explanation: "Imala yeroo gabaabaaf." },
    { english: "Luggage", oromo: "Fe'aa", example: "Don't forget your luggage.", exampleOromo: "Fe'aa kee hin dagatiin.", explanation: "Waan imala waliin fudhannu." },
    { english: "Passport", oromo: "Paaspoortii", example: "You need a passport to travel abroad.", exampleOromo: "Biyya alaatti imaluuf paaspoortii barbaachisa.", explanation: "Waan eenyummaa biyya alaatti imaluuf." },
    { english: "Hotel", oromo: "Hoteela", example: "We stayed at a nice hotel.", exampleOromo: "Hoteela gaarii keessa turre.", explanation: "Bakka imaltoonni itti buluu." },
    { english: "Destination", oromo: "Bakka itti deemnu", example: "We reached our destination safely.", exampleOromo: "Bakka itti deemnu nagaan geenye.", explanation: "Bakka dhumaa imalaa." }
  ]
};