const LESSON_7 = {
  id: 7,
  title: "Nyaata fi Dhugaatii",
  titleEnglish: "Food & Drinks",
  icon: "🍽️",
  level: "gidduu",
  words: [
    { english: "Food", oromo: "Nyaata", example: "The food is delicious.", exampleOromo: "Nyaatni kun mi'aawa dha.", explanation: "Waan nyaannu hundaa." },
    { english: "Drink", oromo: "Dhugaatii", example: "I need a drink.", exampleOromo: "Dhugaatii nan barbaada.", explanation: "Waan dhugnu hundaa." },
    { english: "Water", oromo: "Bishaan", example: "Give me water.", exampleOromo: "Bishaan naaf kenni.", explanation: "Dhugaatii bu'uuraa." },
    { english: "Bread", oromo: "Buddeena", example: "I eat bread for breakfast.", exampleOromo: "Ganama buddeena nyaadha.", explanation: "Nyaata daqiiqaa irraa hojjetame." },
    { english: "Rice", oromo: "Ruuzii", example: "We eat rice with meat.", exampleOromo: "Foonii fi ruuzii nyaanna.", explanation: "Midhaan adii xiqqoo." },
    { english: "Meat", oromo: "Foon", example: "The meat is cooked.", exampleOromo: "Fooni bilchaateera.", explanation: "Foon loon ykn hoolaa." },
    { english: "Fish", oromo: "Qurxummii", example: "Fish is healthy.", exampleOromo: "Qurxummiin fayyaaf gaarii dha.", explanation: "Binelda bishaanii nyaatamu." },
    { english: "Egg", oromo: "Hanqaaquu", example: "I eat an egg every morning.", exampleOromo: "Ganama hundaa hanqaaquu nyaadha.", explanation: "Lukkuu irraa argamu." },
    { english: "Milk", oromo: "Aannan", example: "Children drink milk.", exampleOromo: "Ijoolleen aannan dhugu.", explanation: "Loon irraa argamu." },
    { english: "Tea", oromo: "Bunaa / Chaayii", example: "Do you want tea?", exampleOromo: "Chaayii barbaaddaa?", explanation: "Dhugaatii ho'aa." },
    { english: "Coffee", oromo: "Bunaa", example: "Ethiopian coffee is famous.", exampleOromo: "Bunaan Itoophiyaa beekamaa dha.", explanation: "Dhugaatii beekamaa Itoophiyaa." },
    { english: "Sugar", oromo: "Shukkaara", example: "Add sugar to the tea.", exampleOromo: "Chaayiitti shukkaara itti dabalaa.", explanation: "Waan mi'aawaa taasisu." },
    { english: "Salt", oromo: "Soogidda", example: "The food needs salt.", exampleOromo: "Nyaatni soogidda barbaada.", explanation: "Waan nyaataaf mi'aawu." },
    { english: "Oil", oromo: "Zayitii", example: "Cook with oil.", exampleOromo: "Zayitiin bilchisi.", explanation: "Waan nyaataaf fayyadamnu." },
    { english: "Fruit", oromo: "Mudura", example: "Eat fruits daily.", exampleOromo: "Guyyaa hundaa mudura nyaadhaa.", explanation: "Muka irraa argamu." },
    { english: "Apple", oromo: "Xaafii", example: "The apple is red.", exampleOromo: "Xaafiin diimaa dha.", explanation: "Mudura beekamaa." },
    { english: "Banana", oromo: "Muuzii", example: "I like bananas.", exampleOromo: "Muuzii nan jaaladha.", explanation: "Mudura keelloo." },
    { english: "Orange", oromo: "Burtukaana", example: "Orange has vitamin C.", exampleOromo: "Burtukaanni vitaamin C qaba.", explanation: "Mudura Burtukaana." },
    { english: "Vegetable", oromo: "Kuduraa", example: "Vegetables are healthy.", exampleOromo: "Kuduraan fayyaaf gaarii dha.", explanation: "Biqiltuu nyaatamu." },
    { english: "Potato", oromo: "Buqqolisaa", example: "I cooked potatoes.", exampleOromo: "Buqqolisaa nan bilchise.", explanation: "Lafa keessaa argamu." },
    { english: "Tomato", oromo: "Timaatima", example: "Tomato is in the salad.", exampleOromo: "Timaatimi salaada keessa jira.", explanation: "Kuduraa diimtuu." },
    { english: "Onion", oromo: "Qullubbii", example: "Onion has strong smell.", exampleOromo: "Qullubbiin fool cimaa qaba.", explanation: "Kuduraa nyaataaf barbaachisuu." },
    { english: "Breakfast", oromo: "Afduu / Ganama", example: "I eat breakfast at 7.", exampleOromo: "Sa'aatii torba afduu nyaadha.", explanation: "Nyaata ganamaa." },
    { english: "Lunch", oromo: "Nyaata guyyaa", example: "Lunch is at noon.", exampleOromo: "Nyaatni guyyaa sa'aatii ja'atti.", explanation: "Nyaata guyyaa walakkaa." },
    { english: "Dinner", oromo: "Nyaata galgalaa", example: "We eat dinner together.", exampleOromo: "Nyaata galgalaa waliin nyaanna.", explanation: "Nyaata galgala." },
    { english: "Hungry", oromo: "Beela'uu", example: "I am hungry.", exampleOromo: "Nan beela'eera.", explanation: "Nyaata barbaaduu." },
    { english: "Thirsty", oromo: "Dheebotuu", example: "I am thirsty.", exampleOromo: "Nan dheeboteera.", explanation: "Bishaan barbaaduu." },
    { english: "Delicious", oromo: "Mi'aawaa", example: "The food is delicious.", exampleOromo: "Nyaatni mi'aawaa dha.", explanation: "Kan mi'a gaarii qabu." },
    { english: "Cook", oromo: "Bilchisuu", example: "She cooks well.", exampleOromo: "Isheen gaarii bilchessiti.", explanation: "Nyaata qopheessuu." },
    { english: "Eat", oromo: "Nyaachuu", example: "Let's eat together.", exampleOromo: "Waliin nyaannu.", explanation: "Nyaata afaaniin fudhachuu." }
  ]
};